# This is for creating directory and naming files.
name_of_test='adamB128'
batch_size=128
epochs=10

[activation_function]
name='relu'

[optimizer]
name='adam'
learning_rate=0.001
beta1=0.9
beta2=0.999

#[optimizer]
#name='sgd'
#learning_rate=0.001
#momentum=0.9
#nesterov=true

#[optimizer]
#name='rmsprop'
#learning_rate=0.001
#momentum=0.9
#alpha=0.999


