# This is for creating directory and naming files.
name_of_test='sgd_0.01_0.9_momentum'
batch_size=64
epochs=10

[activation_function]
name='relu'

# [optimizer]
# name='adam'
# learning_rate=0.001
# beta1=0.9
# beta2=0.999

[optimizer]
name='sgd'
learning_rate=0.01
momentum=0.9
nesterov=true

# [optimizer]
# name='rmsprop'
# learning_rate=0.001
# momentum=0.9
# alpha=0.999


