# This is for creating directory and naming files.
name_of_test='relu_64_20_0.001'
batch_size=64
epochs=20

[activation_function]
name='relu'

[optimizer]
name='adam'
learning_rate=0.001
beta1=0.9
beta2=0.999

# [optimizer]
# name='sgd'
# learning_rate=0.001
# momentum
# nesterov=True/False

# [optimizer]
# name='rmsprop'
# learning_rate=0.001
# momentum=0.9
# alpha=0.999


