version: 1

defaults:
  experiment_name: "test"

optimizer:
  name: "adam"
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.999

architecture:
  convolution_layer_1:
    - type: "conv2d"
      in_channels: 3
      out_channels: 64
      kernel_size: 3
      stride: 1
      padding: 1
      activation: "relu"
